"""init

Revision ID: 5aeabc3c17c9
Revises:
Create Date: 2026-07-13 22:39:20.270637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5aeabc3c17c9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rsa_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("public_key_pem", sa.Text(), nullable=False),
        sa.Column("private_key_pem", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("initialized", sa.Boolean(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=False),
        sa.Column("signature", sa.String(length=500), nullable=True),
        sa.Column("avatar_path", sa.String(length=500), nullable=True),
        sa.Column("role", sa.String(length=20), server_default="user", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("can_invite", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("failed_login_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'user')", name="ck_users_role"),
        sa.CheckConstraint(
            "status IN ('active', 'deactivated', 'disabled')", name="ck_users_status"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_status", ["status"], unique=False)

    op.create_table(
        "file_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.CheckConstraint(
            "kind IN ('image', 'video', 'avatar', 'thumb', 'large')", name="ck_file_metadata_kind"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_path"),
    )
    op.create_table(
        "friendships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_a_id", sa.Integer(), nullable=False),
        sa.Column("user_b_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("requester_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("status IN ('pending', 'accepted')", name="ck_friendships_status"),
        sa.CheckConstraint("user_a_id < user_b_id", name="ck_friendships_user_order"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_a_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_b_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_a_id", "user_b_id", name="uq_friendships_users"),
    )
    op.create_table(
        "invite_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'used', 'expired', 'revoked')", name="ck_invite_codes_status"
        ),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["used_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.create_index("ix_invite_codes_creator_id", ["creator_id"], unique=False)
        batch_op.create_index("ix_invite_codes_status", ["status"], unique=False)

    op.create_table(
        "likes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.CheckConstraint("target_type IN ('post', 'comment')", name="ck_likes_target_type"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", "user_id", name="uq_likes_target_user"),
    )
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.create_index("ix_likes_target", ["target_type", "target_id"], unique=False)

    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=20), server_default="public", nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("visibility IN ('public', 'friends')", name="ck_posts_visibility"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index("ix_posts_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_posts_deleted_at", ["deleted_at"], unique=False)
        batch_op.create_index("ix_posts_user_id", ["user_id"], unique=False)

    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("parent_comment_id", sa.Integer(), nullable=True),
        sa.Column("reply_to_user_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=500), nullable=True),
        sa.Column("image_thumb_path", sa.String(length=500), nullable=True),
        sa.Column("image_large_path", sa.String(length=500), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reply_to_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index("ix_comments_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_comments_post_id", ["post_id"], unique=False)

    op.create_table(
        "post_media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("thumb_path", sa.String(length=500), nullable=False),
        sa.Column("large_path", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default="CURRENT_TIMESTAMP", nullable=False),
        sa.CheckConstraint("kind IN ('image', 'video')", name="ck_post_media_kind"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post_media", schema=None) as batch_op:
        batch_op.create_index("ix_post_media_post_id", ["post_id"], unique=False)

    # ### end Alembic commands ###

    op.get_bind().execute(
        sa.text(
            "INSERT INTO system_status (id, initialized, admin_user_id, created_at, updated_at) "
            "VALUES (1, 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post_media", schema=None) as batch_op:
        batch_op.drop_index("ix_post_media_post_id")

    op.drop_table("post_media")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index("ix_comments_post_id")
        batch_op.drop_index("ix_comments_created_at")

    op.drop_table("comments")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index("ix_posts_user_id")
        batch_op.drop_index("ix_posts_deleted_at")
        batch_op.drop_index("ix_posts_created_at")

    op.drop_table("posts")
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_index("ix_likes_target")

    op.drop_table("likes")
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.drop_index("ix_invite_codes_status")
        batch_op.drop_index("ix_invite_codes_creator_id")

    op.drop_table("invite_codes")
    op.drop_table("friendships")
    op.drop_table("file_metadata")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_status")

    op.drop_table("users")
    op.drop_table("system_status")
    op.drop_table("rsa_keys")
    # ### end Alembic commands ###
